[package]
build = 'build.rs'
edition = '2021'
name = 'ton_labs_assembler'
version = '1.4.15'

[dependencies]
failure = '0.1'
hex = '0.4'
log = '0.4'
num = '0.4'
num-traits = '0.2'
serde_json = '1.0'
clap = { features = [ 'derive' ], version = '4.3' }
serde = { features = [ 'derive' ], version = '1.0' }
ton_types = { git = 'https://github.com/tonlabs/ever-types.git', tag = '2.0.28' }
ton_vm = { git = 'https://github.com/gosh-sh/ever-vm.git', branch = 'feature/gosh_hash' }

[features]
gosh = [  ]
groth = [  ]

